### PR TITLE
Stringlist branch

### PR DESCRIPTION
**Pull request by SteelMatrix**
Hello @svaldez85,
We'll merge your branch first, then merge mine on top. After that, we can debug the memory errors using valgrind. I will be able to start the merge process tomorrow, but if you want to merge your branch into the master, feel free to do so.
Thanks,
@SteelMatrix

### CODE REVIEW

**Comment by lilacnight** [comment]
sorry I've been MIA john i was at that coding competition. Do you want to merge these branches now? I looked and unique is really the only conflict could keep either your version or mine. both work so whichever you think is better.

**Comment by lilacnight** [comment]
I'm trying to fix the push_back/front issues but I'm not having any luck. I'm going to try and fix some of the memory leaks in the master branch

**Comment by lilacnight** [comment]
Actually I'm not getting any memory problems in the master branch are you sure there are leaks?

**Comment by SteelMatrix** [comment]
Apparently, the master branch has no issues. I'll close this merge request after I see what is different between this branch and mine.

**Comment by SteelMatrix** [comment]
Hello @svaldez85,
Upon pulling and running the code from the master branch, I keep getting a segmentation fault error. I'm not sure what the difference is, but with my code there aren't any segmentation faults, just leaks. If possible, could you run the code on your machine from the master branch and the stringlist-branch?
Thanks,
@SteelMatrix

**Comment by lilacnight** [comment]
I'm not getting any errors on the master branch still just a second

**Comment by SteelMatrix** [comment]
Just to be sure, make sure that in the runtests.cpp, the first "if" statement is set to 1. If it's set to 0, then it will use the default library.

**Comment by lilacnight** [comment]
Alright I'm getting leaks on your branch

**Comment by lilacnight** [comment]
And now the master is really experiencing some issues. Let me look at the leaks on your branch real quick

**Comment by SteelMatrix** [comment]
The leaks are mostly in pop_back and pop_front now. I fixed the reverse by not making new pointers.

**Comment by SteelMatrix** [comment]
My mistake, the leaks are in push_back and push_front. Namely, when creating the new pointers, it doesn't free them at the end.

**Comment by lilacnight** [comment]
Oh okay I just ficed the reverse too whoops haha

**Comment by lilacnight** [comment]
I think I know what might be wrong. Is back one past the end or is it the end?

**Comment by SteelMatrix** [comment]
It should be the end, not one past, because we defined the _back variable to be the end. I just pushed my most recent code, so feel free to check that out.

**Comment by SteelMatrix** [comment]
If we could somehow do the push_back and push_front without creating the new llist, we should be able to pass the valgrind test.

**Comment by lilacnight** [comment]
I think what we need to do is make a destructor for the struct llist since the machine doesn't know how to delete it

**Comment by SteelMatrix** [comment]
Alright, I'll try that. I'll let you know if it works.

**Comment by lilacnight** [comment]
I'm trying it now no luck yet

**Comment by SteelMatrix** [comment]
I think at this point, we should just merge it, then continue to see if we have issues. Sounds good?

**Comment by SteelMatrix** [comment]
It's definitely push_back and push_front. Run the command `valgrind -v --leak-check=full ./runtests`, it will show the functions that are causing the issue. Lines 112 and 98 on the most recently updated code on stringlist branch.

**Comment by lilacnight** [comment]
Yeah I'm not getting anywhere. I changed the std::string str being pulled into push_front and push_back into references but doesn't seem to have helped any. I'm at lost 221 allocs and 208 frees. you?

**Comment by SteelMatrix** [comment]
I've got 29 allocs and 16 frees on my machine, on the stringlist branch.

**Comment by lilacnight** [comment]
oh nevermind me too i read the wrong line

**Comment by SteelMatrix** [comment]
Alright, I'll go ahead and merge. Just in case we cannot solve the issue, we can still get the points.

**Comment by lilacnight** [comment]
okay I'll merge after you just to change those strs to const references

**Comment by SteelMatrix** [comment]
I'm going to leave the branch, so he can see our progress

**Comment by SteelMatrix** [comment]
Whoops, I just noticed your post. I'll go and fix those.

**Comment by lilacnight** [comment]
Okay, I'll try and figure those leaks out tonight.

**Comment by SteelMatrix** [comment]
I'm going to retire from this assignment for about an hour and a half. I need a break from it, but I'll return, hopefully refreshed.

**Comment by SteelMatrix** [comment]
Hello @svaldez85,
After coming back, I've determined the following. It might just be a recap, but here it goes:
1. The issue is that the memory leaks come from the new structs that are created.
2. The structs that are created cannot be deleted, otherwise it causes a segmentation error.

The solution to this might be to not make new structs, delete them properly, or make a pointer near where we made the _front and _back, and use that one as a temporary variable. I've tried the method of not making structs, without success, so let's try the other two options.
Here's hoping,
@SteelMatrix

**Pull request merged**
